### ISSUE TITLE
Latest PlayStore Version crashed after Launch

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab.android#330]
After the newest Update it starts up and then shows the sitemap. After about 1 second it just exits.

**Comment by mueller-ma** [comment]
Are you using ssl client authentication?

**Comment by Flole998** [comment]
No, i am using SSL but not SSL Client authentication using a certificate. I am using Basic authentication though.

**Comment by mueller-ma** [comment]
Can you try to clear the app data?

**Comment by Flole998** [comment]
Clearing App Data is clearly not a fix, that's a sketchy workaround. The source of the issue should be investigated.

**Comment by Flole998** [comment]
The issue is a nullpointer exception as android.graphics.RectF.wifth() is called on a non-existent Image at org.openhab.habdroid.util.MyWebImage.getBitmapFromSvgInputstream(MyWebImage.java:146)

I think the image in my sitemap is non-existent, however this should not lead to a crash.

**Comment by mueller-ma** [comment]
A non existing picture or icon? Do you use svg icons?

**Comment by mueller-ma** [comment]
I have set the icon format to svg, but I do not have a svg version for all my icons. It crashed on Android 5 and 7.1.2. This log is from 5:

```
07-15 20:06:27.366 19880-19880/org.openhab.habdroid D/AndroidRuntime: Shutting down VM
07-15 20:06:27.367 19880-19880/org.openhab.habdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.openhab.habdroid, PID: 19880
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.makeRadialGradient(SVGAndroidRenderer.java:3360)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.decodePaintReference(SVGAndroidRenderer.java:3178)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.checkForGradientsAndPatterns(SVGAndroidRenderer.java:3148)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1063)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:301)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:333)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:616)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:297)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:333)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:616)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:297)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:333)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:587)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:270)
                                                                          at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:406)
                                                                          at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:384)
                                                                          at org.openhab.habdroid.util.MyWebImage.getBitmapFromSvgInputstream(MyWebImage.java:152)
                                                                          at org.openhab.habdroid.util.MyWebImage.getBitmapFromInputStream(MyWebImage.java:135)
                                                                          at org.openhab.habdroid.util.MyWebImage.access$000(MyWebImage.java:35)
                                                                          at org.openhab.habdroid.util.MyWebImage$1.onSuccess(MyWebImage.java:107)
                                                                          at org.openhab.habdroid.util.MyAsyncHttpClient$1$2.run(MyAsyncHttpClient.java:70)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by FlorianSW** [comment]
I get a slightly different stack trace:
```
07-15 23:15:23.683 4131-4131/org.openhab.habdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: org.openhab.habdroid, PID: 4131
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'float android.graphics.RectF.width()' on a null object reference
                                                                        at org.openhab.habdroid.util.MyWebImage.getBitmapFromSvgInputstream(MyWebImage.java:146)
                                                                        at org.openhab.habdroid.util.MyWebImage.getBitmapFromInputStream(MyWebImage.java:135)
                                                                        at org.openhab.habdroid.util.MyWebImage.access$000(MyWebImage.java:35)
                                                                        at org.openhab.habdroid.util.MyWebImage$1.onSuccess(MyWebImage.java:107)
                                                                        at org.openhab.habdroid.util.MyAsyncHttpClient$1$2.run(MyAsyncHttpClient.java:70)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

As this is reasonable, as `SVG#getDocumentViewBox` can return null, I'll submit a PR, which should fix this issue. However, it would be great to get a verification, that this is really the problem of @Flole998 :)

**Comment by Flole998** [comment]
Stacktrace of @FlorianSW is the same I receive.

**Comment by FlorianSW** [comment]
The net question is: If an SVG image does not exist, why openHAB sends the 200 OK status code for the image request:
http://192.168.178.27:8080/icon/big_bulb1?state=null&format=SVG
-> will result in 200 OK, even if there's no SVG image with the name big_bulb1 and even not a PNG one, which also returns 200. If it would return 404 or something else, the app would call the onFailure method for that request and would not try to get an image out of the InputStream.

**Comment by FlorianSW** [comment]
Reported as https://github.com/eclipse/smarthome/issues/3842
