### ISSUE TITLE
Crash with PR: Number picker for setpoint

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab.android#468]
https://github.com/openhab/openhab.android/pull/442/files#diff-7084e55d51f6579524d6f8ef39d55555R705

@boc-tothefuture I did not test this when I merged, but now that I'm testing something else I'm getting a app crash on our demo site:

```
11-26 14:18:13.084 25000-25000/org.openhab.habdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.openhab.habdroid, PID: 25000
                                                                      java.lang.ArithmeticException: divide by zero
                                                                          at org.openhab.habdroid.ui.OpenHABWidgetAdapter$12.onClick(OpenHABWidgetAdapter.java:705)
                                                                          at android.view.View.performClick(View.java:5204)
                                                                          at android.view.View$PerformClick.run(View.java:21153)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-26 14:19:12.534 25000-25062/org.openhab.habdroid I/MyWebImage: fetched bitmap for https://myopenhab.org/icon/rollershutter?state=ON&format=PNG
11-26 14:19:12.635 25000-25065/org.openhab.habdroid I/MyWebImage: fetched bitmap for https://myopenhab.org/icon/rollershutter?state=100&format=PNG
```

**Comment by boc-tothefuture** [comment]
Will take a look.  Do you know your min/max/step and value range for that setpoint?

I am running the main branch build here and it's working so I must not be handling some particular input correctly.

**Comment by mueller-ma** [comment]
I also noticed that the app may crash, so I opened https://github.com/eclipse/smarthome/issues/4498 to add server side tests. I don't think the app has to do those checks, but the app will release before such tests.

**Comment by digitaldan** [comment]
@boc-tothefuture I can reproduce this on demo.openhab.org , go to "Widget Overview" and then click on the value of "Temperature" (so click the 21.5 c value, or whatever it is)

**Comment by boc-tothefuture** [comment]
@digitaldan - PR #469 should resolve this error.

**Comment by digitaldan** [comment]
I'll give it a try, I posted here b/c I could not remember where I had it crash on me, but just ran into it again.
